# Generated by Django 5.0.8 on 2024-08-07 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Presidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('inicio', models.IntegerField()),
                ('final', models.IntegerField()),
                ('description', models.TextField()),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.partido')),
            ],
        ),
    ]
